name: raven_ai
channels:
  - conda-forge
dependencies:
  - python
  - fastapi
  - fastmcp
  - uvicorn
  # docs
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid
  - myst-parser  # required for parsing markdown files
  - pip
  - pip:
    - ravendb
    - pyravendb